server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          my-oidc-client:
            provider: my-oidc-provider
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: openid,profile,message.read,message.write
        provider:
          my-oidc-provider:
            issuer-uri: http://localhost:9000


app:
  resource-server:
    base-url: http://localhost:8090


logging:
  level:
    org.springframework.security: info
